spring:
  main:
    banner-mode: "off"
server:
  port : 9095

data:
  environment:
    # Load   WhiteRaven  DFQL
    name: "Load"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.golan: TRACE
    org.springframework.web: TRACE
    com.howtodoinjava: INFO
    org.hibernate: ERROR
